### ISSUE TITLE
default config file location

### ISSUE THREAD

**Issue by laalsaas** [zsugabubus/mbidled#1]
The configuration file for isync per default resides in `~/.mbsyncrc`. (Or, for future versions, in `$XDG_CONFIG_HOME/isyncrc` (for details see commit `cf13630a0` in isync.)). I propose to implement these default locations in mbidled, so `-c` doesn't need to be specified always, only when you want to override the default locations.

**Comment by zsugabubus** [comment]
Thanks for the feedback. Done in ca22d0ea9ac68c4f177ca148e137691758b515fd.
